CREATE DATABASE lost_found_db;
USE lost_found_db;
CREATE TABLE LOST_ITEMS
(
    ITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
    ITEM_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT,
    LOCATION VARCHAR(100) NOT NULL,
    DATE_LOST DATE NOT NULL,
    CONTACT_NUMBER VARCHAR(15) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'LOST'
);

CREATE TABLE FOUND_ITEMS
(
    ITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
    ITEM_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT,
    LOCATION VARCHAR(100) NOT NULL,
    DATE_FOUND DATE NOT NULL,
    CONTACT_NUMBER VARCHAR(15) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'FOUND'
);


SHOW TABLES;
DESC LOST_ITEMS;

INSERT INTO LOST_ITEMS VALUES (1,'BLACK WALLET', 'ACCESSORIES', 'LEATHER WALLET WITH ID CARDS', 'NEAR MAIN BUILDING', '2026-07-15', '9876543210','LOST');
INSERT INTO LOST_ITEMS VALUES(2,'SAMSUNG MOBILE', 'ELECTRONICS', 'BLACK SAMSUNG GALAXY PHONE', 'COLLEGE CAMPUS', '2026-07-14', '9123456789','LOST'),
(3,'BLUE BACKPACK', 'BAGS', 'BACKPACK WITH BOOKS', 'NEAR CANTEEN', '2026-07-13', '9988776655','LOST');

SELECT * FROM LOST_ITEMS;

INSERT INTO FOUND_ITEMS VALUES
(1,'SILVER WATCH', 'ACCESSORIES', 'SILVER TITAN WATCH', 'SWARGATE', '2026-07-15', '9876543211','FOUND'),
(2,'BLACK WALLET', 'ACCESSORIES', 'WALLET WITH AADHAR CARD', 'FC ROAD', '2026-07-14', '9876543212','FOUND'),
(3,'DELL LAPTOP', 'ELECTRONICS', 'BLACK DELL LAPTOP', 'COLLEGE LIBRARY', '2026-07-13', '9876543213','FOUND'),
(4,'HOUSE KEYS', 'KEYS', 'KEYCHAIN WITH THREE KEYS', 'KOTHRUD', '2026-07-12', '9876543214','FOUND'),
(5,'BLUE WATER BOTTLE', 'PERSONAL', '1 LITRE BOTTLE', 'COLLEGE CANTEEN', '2026-07-11', '9876543215','FOUND');


SELECT * FROM FOUND_ITEMS;


CREATE TABLE USERS
(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    FULL_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    ROLE VARCHAR(20) DEFAULT 'USER'
);

select * from USERS;

CREATE TABLE CLAIMS
(
    CLAIM_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    ITEM_ID INT,
    ITEM_TYPE VARCHAR(10),
    CLAIM_DATE DATEss,
    STATUS VARCHAR(20) DEFAULT 'PENDING'
);


CREATE TABLE ADMIN
(
    ADMIN_ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(100)
);
